version: "3.8"
services:
  backend-flask:
    container_name: backend-flask
    env_file:
      - .env
    build: ./backend-flask
    ports:
      - "4567:4567"
    depends_on:
      db:
        condition: service_healthy
      ddb:
        condition: service_healthy
    volumes:
      - ./backend-flask:/backend-flask
    networks:
      - default-network
  frontend-react-js:
    container_name: frontend-react-js
    env_file:
      - .env
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
    networks:
      - default-network
  db:
    container_name: db
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - db:/var/lib/postgresql/data  
    networks:
      - default-network
  ddb:
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # We needed to add user:root to get this working.
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: ddb
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'if [ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]; then exit 0; else exit 1; fi',
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - default-network

  xray-daemon:
    container_name: x-ray-daemon
    image: "amazon/aws-xray-daemon"
    env_file:
      - .env
    command:
      - "xray -o -b xray-daemon:2000"
    ports:
      - 2000:2000/udp
    networks:
      - default-network

# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks:
  default-network:
    driver: bridge
    name: cruddur-net

volumes:
  db:
    driver: local
