tasks:
  set-env-id:
    name: Set Environment Variables
    command: |
      # Persistent IDs
      export GITPOD_ENV_ID=$(gitpod whoami | grep "User ID:" | awk '{print $3}')

      # Networking
      export GITPOD_IP=$(curl -s ifconfig.me)
      export DB_SG_ID="sg-09aecc0b76a75ec38"
      export DB_SG_RULE_ID="sgr-0974283630148b03f"

      # RDS Credentials
      export PG_HOSTNAME='cruddur-db-instance.cxaqmw4euj66.ca-central-1.rds.amazonaws.com'
      export PG_DATABASE='cruddur'
      export PG_USERNAME='root'
      export PG_PASSWORD='goodPassword123'

      # Construct Connection URL dynamically
      export CONNECTION_URL="postgresql://$PG_USERNAME:$PG_PASSWORD@$PG_HOSTNAME:5432/$PG_DATABASE"

      # Persist all to bashrc for subshells
      cat <<EOF >> ~/.bashrc
      export GITPOD_ENV_ID=$GITPOD_ENV_ID
      export GITPOD_IP=$GITPOD_IP
      export DB_SG_ID=$DB_SG_ID
      export DB_SG_RULE_ID=$DB_SG_RULE_ID
      export PG_HOSTNAME=$PG_HOSTNAME
      export PG_DATABASE=$PG_DATABASE
      export PG_USERNAME=$PG_USERNAME
      export PG_PASSWORD=$PG_PASSWORD
      export CONNECTION_URL=$CONNECTION_URL
      EOF
    triggeredBy:
      - postDevcontainerStart

  install:
    name: Install npm dependencies
    command: |
      cd frontend-react-js
      npm install
    triggeredBy:
      - postDevcontainerStart

  startup-commands:
    name: Update RDS Security Group
    command: |
      cd backend-flask
      chmod +x ./bin/rds-update-sg-rule
      ./bin/rds-update-sg-rule
