tasks:
  set-env-id:
    name: Get and Set env vars
    command: |
      export GITPOD_ENV_ID=$(gitpod whoami | grep "User ID:" | awk '{print $3}')
      echo "export GITPOD_ENV_ID" >> ~/.bashrc
      CONNECTION_URL='postgresql://postgres:password@localhost:5432/cruddur'"
      export CONNECTION_URL >> ~/.bashrc
    triggeredBy:
      - postDevcontainerStart
  Install:
    name: Install npm dependencies
    command: |
      cd frontend-react-js
      npm install
    triggeredBy:
      - postDevcontainerStart
